Phase02
Mohaymen-Academy/SE_Team05_Summer1402 pull request #1
Opened 2023-07-19 11:39 UTC by MSPoulaei

2023-07-19 12:19 UTC, Ali-Athary commented
1. getDataPath and setDataPath in FolderPathis not used and redundent.
2. InvertedIndex violates Single Responsibility princilpe and should not handel normalization.

2023-07-19 12:56 UTC, Kiasoh commented
temp variables (for example InvertedIndex Line 14 , 34 , 30 , 21 ...)

2023-07-20 15:50 UTC, Soltaniant requested changes
لطفا ایرادات را تا روز شنبه اصلاح نکنید.

نکات زیادی وجود داشت که باید دوباره به آنها بیندیشید. سعی کنید بیشتر روی core سرویس تمرکز کنید و ابتدا آن را تمیز کنید و سپس به مخلفات و دیگر قسمت‌های کم‌اهمیت‌تر (قسمت‌هایی مثل خود کوئری) بپردازید.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/README.md
> +      return text.split(" +");
فکر کنم از رجکس `/s` برای تشخیص whitespace استفاده کنیم بهتر باشه. هرچند مثاله صرفا، اما خوبه که واقعی‌تر باشه. درباره تفاوتشون یه جست‌وجو داشته باشیم.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/README.md
> +   3. Set your stop-words by setStopWords method.
فکر کنم نیازی به این حد از توضیح جزیی برای usage نباشه. به خصوص اینکه در مواردی، توضیحات دانشی رو به مخاطب اضافه نمی‌کنن.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/README.md
> +# Usage
اول اینکه دمتون گرم که readme نوشتین :+1: 
پیشنهادم اینکه یه بخش features هم می‌تونین داشته باشین. چون مهمه، حتی مهم‌تر از usage
در واقع این فیچر‌های شماست که مخاطب رو مشتاق خوندن usage می‌کنه!

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/DefaultNormalizer.java
> +    public String normalize(String token) {
با هر بار فراخوانی تابه normalize داریم یه آبجکت stemmer رو new می‌کنیم. در حالیکه نیاز نیست. کافیه فقط یه stemmer داشته باشیم. نه؟

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/DefaultNormalizer.java
> +public class DefaultNormalizer implements Normalizer {
نام DefaultNormalizer چندان جالب نیست. درسته که این نرمالایزر به عنوان نرمالایزر دیفالت داره استفاده می‌شه، اما خودش قاعدتا اسم مناسبی داره که اسمش باید نشون بده چطور داره نرمالیزیشن رو انجام می‌ده. عبارت default رو میشه جای دیگه‌ای به کار برد.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/DefaultTokenizer.java
> +public class DefaultTokenizer implements Tokenizer {
مشابه DefaultNormalizer

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/Dictionary.java
> +        if (query.isBlank()) return new ArrayList<>();
برای هر بار برگردوندن یه لیست خالی داریم یه new ArrayList فراخوانی می‌کنیم. (مشابه بحث stemmer)

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/Doc.java
> +}
دقاقا داریم چی کار می‌کنیم اینجا؟ :thinking:

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/FileReader.java
> +    public String[] getStopWords(String path) {
وظیفه FileReader این نیست :)
Single Responsibiliy Principle

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/FileReader.java
> +        return new Doc(fileName, fileContent);
تقریبا تنها استفادمون از Doc انگار اینه که اسم و کانتت رو بتونیم همزمان برگردونیم. نه؟
تو خط ۳۲ هم اومدیم Doc رو باز کردیم :|

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/FileReader.java
> +    public HashMap<String, String> getDataset(String path) {
اسم مناسبی نیست. توی FileReader

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/FolderPath.java
> +    }
اگر بخوام از یه فایل text دیگه داده‌ها رو بخونم چی کار کنم؟
باید بیایم این خطا رو عوض کنیم. (کلاس هم singeltone هست)
و اینکه واژه stopWordsPath بازم یه اتفاق general نیست و نباید وارد منطق برناممون بشه.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/FileReader.java
>          HashMap<String, String> fileText = new HashMap<>();
چرا خود Doc رو برنگردوندیم و اومدیم بازش کردیم به name + content؟

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +    public void addDoc(Doc doc, HashMap<String, HashSet<String>> dict) {
یک Doc دارم که می‌خوام به inverted Index اضافش کنم. چرا باید یک پارامتر dict هم بهش پاس بدم؟؟
به طور دقیق‌تر این مشکلی که اینجا هست به خاطر یکی دو لول بالاتر از این کلاسه. درباره middleMan مطالعه کنید. دچارش شدین. و برای رسیدن به invertedIndex مسیر خیلی زیادی رو باید طی کنیم.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +        ArrayList<String> filteredWords = NLP.filterTokens(tokenizedWords);
یا تماما از `String[]` استفاده کنیم. یا تماما از Arraylist
(ترجیحا دومی که امکانات بیشتری در اختیارمون میذاره)

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +        insertNormalizedWords(normalizedWords, dict, doc.title());
نتیجه اون بحث قبلی دوباره اینجا خودش رو نشون میده که ما خیلی به dict وابسته شدیم.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +    private String[] tokenizeDocWords(Doc doc) {
اسم تابع مناسب نیست. words قرار نیست tokenize شود.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +        String content = doc.content();
مستقیما پاس بدهیم به تابع

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +    private ArrayList<String> normalizeDocWords(ArrayList<String> filteredWords) {
نام پارامتر مناسب نیست.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +        for (String filteredToken : filteredWords) {
نام filteredToken و تفاوتش با filteredWords چندان گویا نیست.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +    private void insertNormalizedWords(ArrayList<String> normalizedWords, HashMap<String, HashSet<String>> dict, String title) {
نام تابع: اگر در آینده یک مرحله دیگر بعد از normalize اضافه شود، آیا باز هم نام این تابع مناسب خواهد بود؟
(پیشتر اشاره شد: پارامتر‌ها نباید انقدر باشند، وابستگی زیادی در معماریتان وجود داشته که منجر به چنین چیزی شده است)

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +                HashSet<String> bookList = new HashSet<>();
نام booklist خیلی خاص است.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/InvertedIndex.java
> +        for (String normalized : normalizedWords) {
نامبه تبع نام نامناسب normalizedWords، نام normalized نیز مناسب نیست.
 نام dict نیز همینطور

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/Main.java
> +                .addByFolder("./src/main/resources/Software Books Dataset/");
عبارت زیر را ببینید:
Application().addByFolder("...")
گویا نیست. اضافه کردن فولدر به application چه معنایی دارد؟ آیا در نگاه اول برای خواننده مشخص است. (مسئله middleman را در معماریتان حل کنید و مراقب باشید، در تمیز بودن و جدا کردن کلاس‌ها دچار افراط نشوید(

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/Main.java
> +            watch.start();
ایده زیبایی بود. نمایش time :+1:

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/NLP.java
> +public class NLP {
نام مناسبی نیست اصلا

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/NLP.java
> +    private static String[] stopWords = new FileReader().getStopWords(FolderPath.getInstance().getStopWordsPath());
خود stopWords به خودی خود موضوعیتی ندارد و بهتر است آن‌را ذیل filter بررسی کنید.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/NLP.java
> +    private static String[] stopWords = new FileReader().getStopWords(FolderPath.getInstance().getStopWordsPath());
وابستگی به FileReader

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/NLP.java
> +    private static String[] stopWords = new FileReader().getStopWords(FolderPath.getInstance().getStopWordsPath());
Why Static fields?

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/NLP.java
> +    public static ArrayList<String> filterTokens(String[] tokens) {
Why static methods?

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/QueryHandler.java
> +        String[] parts = query.split(" +");
مشابه کامنتی که در readme گذاشتم.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/QueryHandler.java
> +        ;
:|

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/Tokenizer.java
> +    String[] tokenize(String text);
.

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/QueryHandler.java
> +    public HashSet<String> runQueries(HashMap<String, ArrayList<String>> queries,
مسئله dictionary مجددا

2023-07-20 15:50 UTC, Soltaniant commented on Phase01_Full-Text Search/src/main/java/Util.java
> +    }
در جاوا برای این اشتراک گیری دستور وجود دارد.

2023-07-20 15:50 UTC, Soltaniant requested changes
لطفا ایرادات را تا روز شنبه اصلاح نکنید.

نکات زیادی وجود داشت که باید دوباره به آنها بیندیشید. سعی کنید بیشتر روی core سرویس تمرکز کنید و ابتدا آن را تمیز کنید و سپس به مخلفات و دیگر قسمت‌های کم‌اهمیت‌تر (قسمت‌هایی مثل خود کوئری) بپردازید.

2023-07-29 08:21 UTC, merged